### ISSUE TITLE
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QGraphicsPathItem'

### ISSUE THREAD

**Issue by gvizkelethy** [nelsongt/mfiaDLTS2#1]
I got an MFIA and heard about your DLTS code. I was really happy that you had a python version and wanted to try it. Unfortunately, when I run python mfiaMain.py I get the following error message:

Traceback (most recent call last):
  File "/Users/gvizkel/Downloads/mfia dlts/mfiaDLTS2/mfiaMain.py", line 11, in <module>
    from GraphClass import MultiLine
  File "/Users/gvizkel/Downloads/mfia dlts/mfiaDLTS2/GraphClass.py", line 4, in <module>
    class MultiLine(pg.QtGui.QGraphicsPathItem):
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QGraphicsPathItem'

The same thing happens on both Mac and Windows.
Python: 3.10.4
PyQt5: 5.15.6
pyqt: 0.13.0

George

**Comment by nelsongt** [comment]
Hi, this looks like an error caused by an update to pyqt5, I can update the code to be compliant with the latest version but I have been traveling so it may take some time

**Comment by gvizkelethy** [comment]
Thanks. Whenever you have time for it.

**Comment by nelsongt** [comment]
I was not able to reproduce this. Do you have pyqtgraph package installed?

Here is my result from "pip list" command:

```
attrs             21.4.0
certifi           2022.9.24
jsonref           0.2
jsonschema        4.16.0
mkl-fft           1.3.1
mkl-random        1.2.2
mkl-service       2.4.0
numpy             1.23.1
packaging         21.3
pandas            1.4.3
pip               22.2.2
pyelftools        0.29
PyMeasure         0.10.0
pyparsing         3.0.9
PyQt5             5.15.7
PyQt5-sip         12.11.0
pyqtgraph         0.12.3
pyrsistent        0.18.0
pyserial          3.5
python-dateutil   2.8.2
pytz              2022.4
PyVISA            1.12.0
setuptools        63.4.1
sip               6.6.2
six               1.16.0
toml              0.10.2
typing_extensions 4.4.0
wheel             0.37.1
wincertstore      0.2
zhinst            22.8.3
zhinst-core       22.8.35048
zhinst-toolkit    0.4.3
zhinst-utils      0.1.2
```

**Comment by nelsongt** [comment]
I see that you meant that you have pyqtgraph package version 0.13.0 and I just tested with 0.12.3. In the changelog for 0.13.0 I see some mention about replacing QGraphicsPathItem to PlotCurveItem

If you want to try it soon, downgrade pyqtgraph to 0.12.4 or lower and see if the program will start. I will see about making the code work with 0.13.0 within a few days hopefully.

**Comment by nelsongt** [comment]
It should work for latest pyqtgraph now, the problem was related to a graph speed up trick that wasn't even fully implemented. Graphing performance is an issue when there are many transients to be averaged (many hundreds) and if PC CPU is poor. MATLAB seems to handle plotting large datasets better, but pyqtgraph performance is improving so it should be investigated more if speed up tricks are necessary.

**Comment by gvizkelethy** [comment]
Thank you it is working.
